### PR TITLE
[Chore] Split CSS + Images subfolder

### PR DESCRIPTION
**Pull request by BrutuZ**
Split monolithic `styles.css` into imported modules. Won't affect production as Netlify runs `esbuild` that merges and minifies CSS and JS into single files.

Moved the png icons and `nocover.jpg` to a subfolder

Removed demo `data.json` from production entirely instead of making it an empty file. Cleaner and allows to call the load backup modal as a fallback from the exception.

### CODE REVIEW

**Comment by Animeboynz** [comment]
Damb bro, nice. You basically cloned the in app badges perfectly. 
This is basically just a website version of Mihon at this point xD

**Comment by Animeboynz** [comment]
Just saw you assigned me to this, is there anything you needed me to do?

**Review by Animeboynz — APPROVED** [review]

**Comment by BrutuZ** [comment]
> Damb bro, nice. You basically cloned the in app badges perfectly.
This is basically just a website version of Mihon at this point xD

They are just squares and I copied the color from their theme file (just added a sliiiight transparency).
Short of reading xD

> Just saw you assigned me to this, is there anything you needed me to do?

Not particularly, just a review / sanity-check to see if I didn't mess anything up

**Comment by Animeboynz** [comment]
Next step add a reader 🤣.

**Comment by Animeboynz** [comment]
And Hey, I don't notice anything broken and if there is we can always fix it later.

**Pull request merged**
