### PR TITLE
Remove webkit-scrollbar.

### LINKED ISSUE #16: When zooming in, the side scroll bar is a lot bigger than the bottom scroll bar.

### PR DESCRIPTION
**Pull request by NGB-Was-Taken**
Closes #16

### CODE REVIEW

**Comment by BrutuZ** [comment]
Was about to suggest removing the color and `*` class while at it

**Comment by NGB-Was-Taken** [comment]
I gave that a little thought too but decided against it. The entire website has a default and non user-customizable dark theming to it, so the scrollbar not following the same theme as rest of the website when the user has system theme set to light wasn't appealing to me.

**Comment by BrutuZ** [comment]
I won't argue, but just because these colors are close enough to the default ones on my system 😆

To me the scrollbar is a system element so pages should have no business messing with them beyond the `overflow` rule, but that's a battle already lost back in the old days when scrollbar styles were introduced 😔

**Comment by NGB-Was-Taken** [comment]
> just because these colors are close enough to the default ones on my system

Ah, the classic "works on my machine".

> To me the scrollbar is a system element so pages should have no business messing with them beyond the `overflow` rule

I also tried `color-scheme: dark;` to force dark theme but that somehow seems to mess with the github svg. Maybe you can take a look into that?

**Pull request merged**
