### PR TITLE
Google Analytics

### PR DESCRIPTION
**Pull request by Animeboynz**

### CODE REVIEW

**Comment by Animeboynz** [comment]
And ofc that does not work.

**Comment by BrutuZ** [comment]
But why? ಥ_ಥ

**Comment by Animeboynz** [comment]
Why add analytics or why it does not work?

**Comment by BrutuZ** [comment]
Why analytics

**Comment by Animeboynz** [comment]
IDK really, Just for random stats, could be cool. Ill just close it or now but I do want to add it at some point down the line.

**Comment by AntsyLich** [comment]
I approb

**Pull request closed without merging**
