### PR TITLE
Replace settings icon with material symbol and add a rotation transit…

### PR DESCRIPTION
**Pull request by NGB-Was-Taken**
…ion.

### CODE REVIEW

**Comment by NGB-Was-Taken** [comment]
Didn't notice [be98062](https://github.com/Animeboynz/Mihon-Backup-Viewer/pull/38/commits/be9806262279708b7e68e55b131813da05c5adfa) which would make the transition useless.

**Comment by BrutuZ** [comment]
This gear also looks too thick compared to the previous one. Maybe the `Tune` icon would fit better?

**Comment by NGB-Was-Taken** [comment]
> This gear also looks too thick compared to the previous one. Maybe the `Tune` icon would fit better?

Hmm... I think the `settings` looks better. Maybe with `FILL` disabled? 
image

**Comment by BrutuZ** [comment]
Was about to suggest outlined Settings

**Comment by NGB-Was-Taken** [comment]
> a 200 weight might help too

200 may be too low without fill. 200 with fill looks fine though. Also, maybe should change `font-size` from current 35px to 45px.

**Comment by BrutuZ** [comment]
> Didn't notice [be98062](https://github.com/Animeboynz/Mihon-Backup-Viewer/pull/38/commits/be9806262279708b7e68e55b131813da05c5adfa) which would make the transition useless.

Not a problem anymore 8770e3bbe77c828fd3e32a8c1baed98a155a3bf4

**Comment by NGB-Was-Taken** [comment]
I think I'm going for weight 200, fill 1, and everything else left as it is.
image

**Comment by BrutuZ** [comment]
LGTM 👍

**Comment by BrutuZ** [comment]
Not squashed on merge 😭

**Comment by NGB-Was-Taken** [comment]
> Not squashed on merge 😭

Wait.. I thought settings mentioned on #34 were applied.

**Pull request merged**
