### PR TITLE
Categories as clickable badges

### PR DESCRIPTION
**Pull request by NGB-Was-Taken**

### CODE REVIEW

**Comment by BrutuZ** [comment]
Maybe move it between the Status - Source and the description?

**Comment by NGB-Was-Taken** [comment]
> Maybe move it between the Status - Source and the description?

image
Hmm... I'm not sure. It feels like it creates too much emptiness between the head section and the description.

**Comment by NGB-Was-Taken** [comment]
image
Something like this could work though. I don't know what might happen if the categories cover more than that one line.

**Comment by BrutuZ** [comment]
I tried reducing the margins a little
image

**Comment by NGB-Was-Taken** [comment]
Maybe a little more margin for categories? This is 20px.
image

**Comment by BrutuZ** [comment]
I'll throw a wrench at it, different units!!!
image

**Comment by NGB-Was-Taken** [comment]
> I'll throw a wrench at it, different units!!! image

I'm still in favor of it having a little more margin. `1em` maybe?

P.S. Reminds me of #40. Should have started off with relative units on most of the site.

**Comment by BrutuZ** [comment]
Let's meet in the middle with 0.75em ? xD

I goofed up and took the tags margin along for the ride on one of those images, my bad.

**Comment by NGB-Was-Taken** [comment]
> Let's meet in the middle with 0.75em ?

Sure.

> I goofed up and took the tags margin along for the ride on one of those images, my bad.

Didn't even realize that I was doing the same thing until you mentioned it. xD

**Pull request merged**
